
###
### All books
http://localhost:8080/library/books

###
### Book with given id
http://localhost:8080/library/books/10

###
### Add new Book
POST http://localhost:8080/library/books
Content-Type: application/json

{
"author": "G.R.R. Martin",
"title":  "Gra o tron"
}
